useHostName: true
useIngress: true
useAutoScaling: false
useWorkloadIdentity: true
useSecretsVault: false
useSnowflakeCredentials: false

resource:
  requests:
    memory: '512Mi'
    cpu: '500m'
  limits:
    memory: '1Gi'
    cpu: '1000m'

livenessProbe:
  port: 8080
  healthPath: '/health'
  initialDelaySeconds: 30
  periodSeconds: 60
  failureThreshold: 3

userDefined:
  - name: SERVICE_MESH
    value: velocity
  - name: GOMEMLIMIT
    value: 900MiB
