include:
  - project: 'tcw-group/technology/platform-engineering/development-operations/cicd-configurations'
    ref: 'main'
    file: '/go/pipelines/v4/go-refresher.cloud.pipeline.yml'

variables:
  PROJECT_NAME: 'trade-refresher'
  DEPLOYMENT_NAME: 'trade-refresher'
  OPEN_API_DOCUMENTATION: ''

  ## AKS Tags ####################################################################################
  APPLICATION_OWNER: 'data-engineering'
  APPLICATION_TYPE: 'trade-refresher'
  APPLICATION_SENSITIVITY: 'confidential'
  ################################################################################################

  ## DOCKER CONFIGURATIONS ########################################################################
  CUSTOM_DOCKERFILE: 'false'
  #################################################################################################

  ## DNS Configurations ###########################################################################
  ENABLE_TLS: 'true'
  DOMAIN: trade-refresher
  #################################################################################################

  ## Workload Identity Configurations #############################################################
  ENABLE_WORKLOAD_IDENTITY: 'true'
  NONPROD_AZURE_CLIENT_ID: '6bdee225-974c-48b2-9ab1-c8ff85b88552'
  NONPROD_K8S_SERVICE_ACCT: 'sa-np-positionrefresher'
  PROD_AZURE_CLIENT_ID: 'ed38f1c8-212c-4ac8-8607-02945a6b56fc'
  PROD_K8S_SERVICE_ACCT: 'sa-pd-positionrefresher'
  #################################################################################################

  ## Authorization Configurations #################################################################
  ENABLE_AUTHORIZATIONS: 'false'
  PDPKEY_DEVELOPMENT:
  PDPKEY_QA:
  PDPKEY_PRODUCTION:
  #################################################################################################
